availability_zones:
  - ap-northeast-2a
  - ap-northeast-2b
  - ap-northeast-2c

networks:
  vpc_cidr: 10.100.0.0/16
  subnets:    
    private:
      cidr:
        - 10.100.192.0/20
        - 10.100.224.0/20
        - 10.100.240.0/20
